### ISSUE TITLE
Snippets won't show in cshtml files

### ISSUE THREAD

**Issue by ChrisF23** [AdrianWilczynski/.NETCoreSnippetPack#1]
Hello! I've found a bug while using your extension. It appears that the snippets aren't working for cshtml files because of the language mode. They only work when the language mode is set to html.
Taking a look at your project, I think this can be fixed by adding these two snippets inside package.json:
```
"contributes": {
        "snippets": [
            (...)
            {
                "language": "razor"
                "path": "./snippets/razor.json"
            },
            {
                "language": "aspnetcorerazor"
                "path": "./snippets/razor.json"
            },
        ]
    }
```
Nice extension by the way; Thank you in advance!

**Comment by AdrianWilczynski** [comment]
Hi, I've set it to HTML some time ago when Razor support did crash a lot - so that it works even if you disable Razor support. It seems fine now so I could probably revert it but it should work as-is anyway in HTML parts of .cshtml file.

<img width="960" alt="Snippets" src="https://user-images.githubusercontent.com/31390726/79860376-dc437280-83d2-11ea-9dfa-e4be146eeffa.png">

If I were to just add entries for `aspnetcorerazor` and `razor` (without disabling it for HTML) it would lead to snippets appearing twice in the list (if I remember correctly).

Is C# extension working correctly for you? Do you get regular autocompletion from it in .cshtml files?

**Comment by ChrisF23** [comment]
At first, when I read your response, thought the problem was that my project is a Razor Pages project, so i created an MVC project and the extension worked fine.
Then I created a new Razor Pages project and extension worked too, but it still wouldn't work on my original Razor Pages project.
Finally, I just closed and reopen my original project and the extension started to work again...
You were right, there was something wrong going on with the C# extension. I'm sorry, my bad! 😅
Thank you!
